[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"

dbg-pls = {version = "0.4.1", features = ["colors", "derive"]}

transiter = "0.2.0"

regex = "1.10.2"